export enum NotificationType {
  NEW_MATCH = 'NEW_MATCH',
  NEW_MESSAGE = 'NEW_MESSAGE',
  PROFILE_LIKE = 'PROFILE_LIKE',
  PROFILE_VIEW = 'PROFILE_VIEW',
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  CALL_MISSED = 'CALL_MISSED',
}